### ISSUE TITLE
RyeStalk patch broken

### ISSUE THREAD

**Issue by iTitus** [iTitus/DownfallRelicStats#4]
```
java.lang.NoSuchMethodException: Patch io.github.ititus.downfallRelicStats.patches.relics.RyeStalkInfo$Patch:
No method named [atBattleStart] found on
class [hermit.relics.RyeStalk]
    at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:480)
    at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:383)
    at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:439)
    at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:285)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by iTitus** [comment]
Fixed
